services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetings
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    depends_on:
      - api
    environment:
      - API_BASE_URL=${API_BASE_URL}
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  dbdata:
